### ISSUE TITLE
Want the pre-trained discriminator parameters file

### ISSUE THREAD

**Issue by yasuobinggan** [ewrfcas/Face-Super-Resolution#15]
Hi, what a amazing work! In my application in some low resolution of Asian face, I found that sometimes the eye appears green, I think this is the cause of the dataset, I want to in your training, on the basis of the application of hd Asia face dataset to training again, but I did not have a discriminator training parameters refer to "90000_G.pth", can give me this file? Thank you very much! (PS: I only have one 1080 ti, retraining costs too much)

**Comment by ewrfcas** [comment]
Sorry for late reply. I'm trying to export the discriminator's weights. Please wait for 2~3 days

**Comment by yasuobinggan** [comment]
Thank you very much!

**Comment by ewrfcas** [comment]
The discriminator model is uploaded
