### ISSUE TITLE
 No module named 'models.modules'

### ISSUE THREAD

**Issue by saiamrit** [ewrfcas/Face-Super-Resolution#3]
On running the test.py, code is throwing an error saying  No module named 'models.modules'. There is no modules file in the modules folder.

**Comment by ewrfcas** [comment]
Maybe it is the error of pytorch multi-gpu with DataParallel? Is your pytorch version==1.2.0?

**Comment by saiamrit** [comment]
Yes my pytorch version is 1.3.1 but I donot think it has any thing to do with pytorch version. The error reads : 
 File "/home/saiamrit/Face-Super-Resolution/models/networks.py", line 3, in <module>
    import models.modules.discriminator_vgg_arch as SRGAN_arch
ModuleNotFoundError: No module named 'models.modules'
Which i feel is because the import is expecting a modules file in the models directory which is not present in the original repository. Kindly have a look at it.

**Comment by ewrfcas** [comment]
sorry for missing them, i have updated the codes

**Comment by saiamrit** [comment]
Thank you
